import{a as l,S as c,i}from"./assets/vendor-CucEYOFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const a of document.querySelectorAll('link[rel="modulepreload"]'))t(a);new MutationObserver(a=>{for(const o of a)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&t(s)}).observe(document,{childList:!0,subtree:!0});function n(a){const o={};return a.integrity&&(o.integrity=a.integrity),a.referrerPolicy&&(o.referrerPolicy=a.referrerPolicy),a.crossOrigin==="use-credentials"?o.credentials="include":a.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(a){if(a.ep)return;a.ep=!0;const o=n(a);fetch(a.href,o)}})();function u(e){if(e)return l({method:"get",url:"https://pixabay.com/api/",params:{key:"53619914-87b740f2b3a0dec47a2b3fec9",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,lang:"ua",per_page:9}}).then(r=>r.data.hits);if(e.toLowerCase().trim()===""){let r=[];return Promise.resolve(r)}}const d=new c("ul.gallery a.a-item",{nav:!0,captions:!0,captionsData:"alt",captionsPosition:"bottom",captionType:"attr",sourceAttr:"href",overlay:!0,captionSelector:"img",captionDelay:250});function p(e){const r=e.map(t=>`<li class="item-gallery">
                <a href="${t.largeImageURL}" class="a-item">
                  <img
                    class="img-gallery"
                    src="${t.webformatURL}" data-likes='${t.likes}' data-view='${t.views}' data-comments='${t.comments}' data-downloads='${t.downloads}' data-source="${t.largeImageURL}" alt="${t.tags}"
                  />
                </a>
                <ul class='info'>
                  <li>Likes <span class='info-span'>${t.likes}</span></li>
                  <li>Views <span class="info-span">${t.views}</span></li>
                  <li>Comments <span class="info-span">${t.comments}</span></li>
                  <li>Downloads <span class="info-span">${t.downloads}</span></li>
                </ul>
              </li>`);document.querySelector("ul.gallery").insertAdjacentHTML("afterbegin",r.join("")),d.refresh()}function f(){if(document.querySelector("ul.gallery")){const e=document.querySelector("ul.gallery");e.innerHTML=""}}function m(){const e=document.querySelector("span.loader");if(!e)document.querySelector("form").insertAdjacentHTML("afterend","<span class='loader showLoader'></span>");else if(e)e.classList.add("showLoader");else return}function g(){const e=document.querySelector("span.loader");if(e&&e.classList.contains("showLoader"))e.classList.remove("showLoader");else if(!e)return}const y=document.querySelector('input[name="search-text"]'),h=document.querySelector("form");h.addEventListener("submit",e=>{e.preventDefault(),m(),f(),u(y.value.toLowerCase().trim()).then(r=>{if(r.length===0)i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:" #ef4040;"});else return p(r)}).catch(r=>i.error({message:`Sorry, here ${r}!`,position:"topRight",backgroundColor:" #ef4040;"})).finally(()=>{g()})});
//# sourceMappingURL=index.js.map
