import{a as c,S as l,i}from"./assets/vendor-CucEYOFD.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))t(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const s of a.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&t(s)}).observe(document,{childList:!0,subtree:!0});function n(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function t(r){if(r.ep)return;r.ep=!0;const a=n(r);fetch(r.href,a)}})();function u(e){return c({method:"get",url:"https://pixabay.com/api/",params:{key:"53619914-87b740f2b3a0dec47a2b3fec9",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,lang:"ua",per_page:9}}).then(o=>o.data.hits)}const d=new l("a.a-item",{nav:!0,captions:!0,captionsData:"alt",captionsPosition:"bottom",captionType:"attr",sourceAttr:"href",overlay:!0,captionSelector:"img",captionDelay:250});function p(e){const o=e.map(t=>`<li class="item-gallery">
                <a href="${t.largeImageURL}" class="a-item">
                  <img
                    class="img-gallery"
                    src="${t.webformatURL}" data-likes='${t.likes}' data-view='${t.views}' data-comments='${t.comments}' data-downloads='${t.downloads}' data-source="${t.largeImageURL}" alt="${t.tags}"
                  />
                </a>
                <ul class='info'>
                  <li>Likes <span class='info-span'>${t.likes}</span></li>
                  <li>Views <span class="info-span">${t.views}</span></li>
                  <li>Comments <span class="info-span">${t.comments}</span>
                  <li>Downloads <span class="info-span">${t.downloads}</span></li>
                </ul>
              </li>`);document.querySelector("ul.gallery").insertAdjacentHTML("afterbegin",o.join("")),d.refresh()}function f(){const e=document.querySelector("ul.gallery");e.innerHTML=""}function m(){const e=document.querySelector("span.loader");e||(e=document.createElement("span"),e.classList.add("loader"),document.querySelector("form").insertAdjacentHTML("afterend",e)),e.classList.add("showLoader")}function g(){const e=document.querySelector("span.loader");e&&e.classList.remove("showLoader")}const y=document.querySelector("form");y.addEventListener("submit",e=>{e.preventDefault(),f(),m(),document.querySelector('input[name="search-text"]').value.toLowerCase().trim()!==""&&u(document.querySelector("input[name='search-text']").value.toLowerCase().trim()).then(o=>{g(),o.length===0?i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:" #ef4040;"}):document.querySelector("input[name='search-text']").value!==""?i.error({message:"Sorry, input is empty!",position:"topRight",backgroundColor:" #ef4040;"}):p(o)}).catch(o=>{i.error({message:`Sorry, here ${o}!`,position:"topRight",backgroundColor:" #ef4040;"})})});
//# sourceMappingURL=index.js.map
