import{a as u,S as d,i as n}from"./assets/vendor-CucEYOFD.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function l(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(r){if(r.ep)return;r.ep=!0;const t=l(r);fetch(r.href,t)}})();function p(a){return u({method:"get",url:"https://pixabay.com/api/",params:{key:"53619914-87b740f2b3a0dec47a2b3fec9",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,lang:"ua",per_page:9}}).then(e=>(console.log(e.data.hits),e.data.hits))}const f=new d(".a-item",{nav:!0,captions:!0,captionsData:"attr",captionsPosition:"bottom",captionType:"attr",sourceAttr:"href",overlay:!0,captionSelector:"img",captionDelay:250});function g(a){console.log(a);const e=a.map(o=>`<li class="item-gallery">
                <a href="${o.largeImageURL}" class="a-item">
                  <img
                    class="img-gallery"
                    src="${o.webformatURL}" data-likes='${o.likes}' data-view='${o.views}' data-comments='${o.comments}' data-downloads='${o.downloads}' data-source="${o.largeImageURL}" alt="${o.tags}"
                  />
                </a>
                <ul class='info'>
                  <li>Likes <span class='info-span'>${o.likes}</span></li>
                  <li>Views <span class="info-span">${o.views}</span></li>
                  <li>Comments <span class="info-span">${o.comments}</span>
                  <li>Downloads <span class="info-span">${o.downloads}</span></li>
                </ul>
              </li>`);document.querySelector("ul.gallery").insertAdjacentHTML("afterbegin",e.join("")),console.log(e),f.refresh()}function m(){const a=document.querySelector("ul.gallery");a.innerHTML=""}const s=document.querySelector("span.loader");function y(){s!=0&&s.classList.add("showLoader")}function c(){s!=0&&s.classList.remove("showLoader")}const h=document.querySelector("form");h.addEventListener("submit",a=>{if(a.preventDefault(),m(),y(),document.querySelector('input[name="search-text"]').value.toLowerCase().trim()!=="")p(document.querySelector("input[name='search-text']").value.toLowerCase().trim()).then(e=>(console.log(e),c(),e.length===0&&n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:" #ef4040;"}),e)).catch(e=>{n.error({message:`Sorry, here ${e}!`,position:"topRight",backgroundColor:" #ef4040;"}),c()}).then(e=>{console.log(e),g(e)});else return n.error({message:"Sorry, input is empty!",position:"topRight",backgroundColor:" #ef4040;"})});
//# sourceMappingURL=index.js.map
